tap "aws/tap"
tap "domt4/autoupdate"
tap "grishka/grishka"
tap "homebrew/bundle"

brew "act"
brew "arp-scan"
brew "bitwarden-cli"
brew "gh"
brew "go-task"
brew "lefthook"
brew "mas"
brew "openjdk"
brew "openssl@1.1"
brew "sshpass"
brew "tcl-tk"
brew "terminal-notifier"
brew "sheldon"
brew "starship"
brew "aws/tap/copilot-cli"

cask "amazon-q"
cask "battery"
cask "displaylink"
cask "docker"
cask "google-cloud-sdk"
cask "iterm2"
cask "keyboardcleantool"
cask "logi-options+"
cask "mactex-no-gui"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "neardrop"
cask "notion"
cask "notion-calendar"
cask "pgadmin4"
cask "raycast"
cask "readdle-spark"
cask "sequel-ace"
cask "slack"
cask "stoplight-studio"
cask "ticktick"
cask "visual-studio-code"
cask "vivaldi"
cask "warp"
cask "xquartz"
cask "zoom"
cask "font-plemol-jp-nf"

mas "Bitwarden", id: 1352778147
mas "Hidden Bar", id: 1452453066
mas "RunCat", id: 1429033973
